name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install dependencies
        run: bundle install
      - name: Run checks
        run: bundle exec rake
#      - name: Simplecov Report
#        uses: aki77/simplecov-report-action@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          failedThreshold: 50
